-- Creates the table to store Stripe Connect account details.
-- This allows the application to remember which Stripe accounts have been connected.

CREATE TABLE public.stripe_connections (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  stripe_account_id text not null unique,
  access_token text not null,
  refresh_token text,
  scope text
);

-- Optional: Add a comment to the table for clarity in the Supabase dashboard.
COMMENT ON TABLE public.stripe_connections IS 'Stores OAuth details for connected Stripe accounts.';